# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cppFlags <- function() {
    .Call('RcppBoostCompute_cppFlags', PACKAGE = 'RcppBoostCompute')
}

compute_hello_world <- function() {
    invisible(.Call('RcppBoostCompute_compute_hello_world', PACKAGE = 'RcppBoostCompute'))
}

getBoostComputeEnvironment <- function() {
    .Call('RcppBoostCompute_getBoostComputeEnvironment', PACKAGE = 'RcppBoostCompute')
}

getProgramCache <- function(sexpContext) {
    .Call('RcppBoostCompute_getProgramCache', PACKAGE = 'RcppBoostCompute', sexpContext)
}

copyToDevice <- function(sexpContext, sexpQueue, rVector) {
    .Call('RcppBoostCompute_copyToDevice', PACKAGE = 'RcppBoostCompute', sexpContext, sexpQueue, rVector)
}

copyToHost <- function(rVector) {
    .Call('RcppBoostCompute_copyToHost', PACKAGE = 'RcppBoostCompute', rVector)
}

simpleTransformationReduction <- function(sexpContext, sexpQueue, sexpDeviceVector) {
    .Call('RcppBoostCompute_simpleTransformationReduction', PACKAGE = 'RcppBoostCompute', sexpContext, sexpQueue, sexpDeviceVector)
}

simpleTransformationReductionWithCopy <- function(sexpContext, sexpQueue, rVector) {
    .Call('RcppBoostCompute_simpleTransformationReductionWithCopy', PACKAGE = 'RcppBoostCompute', sexpContext, sexpQueue, rVector)
}

simpleTransformationReductionNoParallel <- function(sexpHostVector) {
    .Call('RcppBoostCompute_simpleTransformationReductionNoParallel', PACKAGE = 'RcppBoostCompute', sexpHostVector)
}

